#!/bin/bash

[ "$*" = "dev" ] && exec mix run -e 'Ghost.Server.main([])'

port=64738

run() {
    echo $@ | nc 127.0.0.1 $port
}

run >/dev/null
if [ $? -ne 0 ]; then 
    ./ghostd
    until run >/dev/null; do
        sleep 0.1
    done
fi
run $@
